#!/usr/bin/env bash
# Configure a new Nginx server so that /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index
sudo bash -c 'cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80;
    server_name default_server;

    location /redirect_me {
        try_files \$uri \$uri/ =404;
    }
    
    location / {
        root /var/www/html;
        index index.html;
    }
}
EOF'
sudo service nginx start
