#!/usr/bin/env bash
# Configure nginx to have a custom 404 page

sudo apt-get update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm

    location /redirect_me {
        return 301 http://cuberule.com/;
    }
    
    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;
    }
}" > /etc/nginx/sites_available/default
sudo service nginx start
