#!/usr/bin/env bash
# Update the system
sudo apt update
sudo apt upgrade -y

# Install HAProxy
sudo apt install haproxy -y

# Configure HAProxy
sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

sudo tee /etc/haproxy/haproxy.cfg > /dev/null << EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web-01 126193-web-01:80 check
    server web-02 126193-web-02:80 check
EOL

# Enable HAProxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAProxy to apply changes
sudo service haproxy restart
