#!/usr/bin/env bash
# A script that pings an IP address passsed as an argument
# Otherwisee ping the IP fiveee times if no argument

if [ $# -eq 0 ]
then
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
else
	ping -c 5 "$1"
fi 
