#!/usr/bin/env bash
# A function that prints the content of the directory password
# Only print the username, id and home directory path

while read -r passwd; do
	echo "$passwd" | cut -d ':' -f1,3,6
done < "etc/passwd"

