#!/usr/bin/env  bash
# A script that iterates through a string with a special print at 9th 

index=0
while [ $index -lt 10 ]
do
	if [ $index -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	((index++))
done
