#!/usr/bin/env bash
# # This script prints "bad luck" 4th iteration, "good luck" on the 8th iteration, and "Holberton School" for other iterations

index=0

while [ $index -lt 20 ]
do 
	echo $index
	case $index in
		4) echo "bad luck from China";;
		9) echo "bad luck from Japan";;
		17) echo "bad luck from Italy";;
	esac
	((index++))
done
