#!/usr/bin/env bash
# A script that print the hour and minute clock

hour=0

while [ $hour -le 12 ]
do
	echo "Hour:$hour"
	minut=1
	
	while [ $minut -le 59 ]
	do
		echo $minut
		((minut++))
	done
	((hour++))
done		
